### ISSUE TITLE
21/10/12 사용가능한 API 목록 수집

### ISSUE THREAD

**Issue by daanta-real** [daanta-real/Hexagram_semi#1]
[사용 API 선정]
본 웹사이트의 참고 DB가 될 여행정보 API를 선정하는 작업.

1. 대한민국구석구석    https://korean.visitkorea.or.kr/main/main.do#home
2. 한국관광데이터랩    https://datalab.visitkorea.or.kr/datalab/portal/main/getMainForm.do
3. 국토교통부관광지    https://www.data.go.kr/data/15058656/openapi.do
4. Tour API    https://api.visitkorea.or.kr/main.do
5. Visit Jeju    https://www.visitjeju.net/kr/visitjejuapi
6. 국내여행코스총정리    https://korean.visitkorea.or.kr/main/cs_main.do
7. 제주투어API    https://tourapi.visitjeju.net/#/intro
8. 트립어드바이저리뷰    https://www.tripadvisor.co.kr/
9. 한국관광공사API    http://2021tourapi.com/sub03.php

**Comment by seonamin** [comment]
7.제주투어API→ 공공데이터포털에서 필요한 오픈 API 활용신청
8.트립어드바이저리뷰→ 리뷰게시판 참고만 가능
9.한국관광공사API→ 공공데이터포털에서 필요한 오픈 API 활용신청

**Comment by hongbba** [comment]
1. 단순 관광정보 홈페이지 (사이트 참고용으로 사용)
2. 추 후 맛집 추가 시 api 활용 (https://www.data.go.kr/data/15081754/openapi.do )
3. 활용사례 확인결과 교통쪽으로 많이 쓰임

**Comment by EUIDONGKIM** [comment]
4. 공공데이터 포털(관광 빅데이터 정보 서비스(인기 관광지 관련) /  한국관광공사 관광사진 정보(관광지 사진 관련) / 노어 관광정보 서비스 & 서어 관광정보 서비스(위치,지역 기반 정보))
5. 제주도 정보(관광지 주소 및 상세정보  / 사진 제공)
6. 저희가 목표로하는 사이트네요.. (4번 목록의 TourAPI / 한국관광공사 / 문화체육관광부 의 정보를 참고했다고 표시되어있네요.)

**Comment by hongbba** [comment]
- 문제점 발견
  - 공공데이터포털에서 받은 API key는 매일 연장신청을 해야함.
  - 아이디를 여러개 사용해야 할 것.
