### ISSUE TITLE
폰트 선정 件

### ISSUE THREAD

**Issue by daanta-real** [daanta-real/Hexagram_semi#12]
가독성에 좋은 폰트를 선정하여 우리 웹사이트에 사용하고자 합니다.
좋은 폰트 있으면 댓글 주세요

**Comment by soeun407** [comment]
<예쁜 글씨체 무료폰트다운 10종>
1.야놀자체
http://yanolja.in/ko/yafont/

2.여기어때 잘난체
https://www.goodchoice.kr/font#is-first

3.스웨거폰트, 스웨거체
http://swagger.kr/font.html

4.tvN 즐거운이야기체
http://tvn10festival.tving.com/playground/tvn10font

5.빙그레체, 빙그레2, 빙그레따옴체, 빙그레 메로나체 4종
http://www.bingfont.co.kr/bingfont.html

6.티몬 몬소리체
https://brunch.co.kr/@creative/32

7.배달의 민족 폰트
https://www.woowahan.com/#fonts

8.페이스샵 잉크립퀴드체
http://www.thefaceshop.com/event/lipquid/main.jsp#FontDownload

9.국대떡볶이체
http://kukde.co.kr/?page_id=627

10.고도디자인 제공 3종-고도체, 고도라운디드, 고도 마음체
https://design.godo.co.kr/custom/free-font.php
