### ISSUE TITLE
기능 추가 제안

### ISSUE THREAD

**Issue by daanta-real** [daanta-real/Hexagram_semi#13]
<기능 추가 제안>
홈/ABOUT US/플래너/탐색/투어/이용방법/FAQ/리뷰/고객센터/로그인

_Originally posted by @soeun407 in https://github.com/daanta-real/Hexagram_semi/issues/11#issuecomment-941964629_

**Comment by hongbba** [comment]
<기능 추가 제안>
각 회원의 페이지를 미니홈피처럼 구현(주제선정때 나왔던 싸이월드)
 - 미니홈피 레이아웃을 또 정하고 그안에 구성을 추가로 하려면 시간이 오래걸릴 것 같으면 제외

**Comment by soeun407** [comment]
고객센터를 넣으면 좋을 것 같습니다.

**Comment by seonamin** [comment]
1. 비회원기능
  - 회원가입
  - 로그인
2. 회원기능(=로그인상태일때)
  - 상세정보
  - 수정 - 비번
  - 수정 - 일반(전체)
  - 아이디 찾기
  - 탈퇴
  - 로그아웃 
3. 관리자용 기능 (=로그인상태일때+관리자일때)
  - 목록 (검색포함)
  - 추가
  - 상세정보
  - 수정 (전체)
  - 탈퇴(시키기)
4. 시간 되면 할 추가기능
  - 포인트 구매/충전/확인 기능
  - 쪽지 기능
  - 아바타 기능
