### ISSUE TITLE
회원(Users) DB / Dao / Dto 설계

### ISSUE THREAD

**Issue by seonamin** [daanta-real/Hexagram_semi#39]
선아 기능구현 중

 - 회원가입 아이디 중복검사
 - 회원가입
 - 로그인
 - 회원정보수정(닉네임, 이메일, 폰번)
 - 비밀번호변경
 - 회원탈퇴
 - 관리자-회원등급수정
 - 관리자-회원전체목록조회

**Comment by daanta-real** [comment]
컬럼 별 제약조건까지 결정 완료.

> 아이디 (usersId) - 준성/선아
```text
^(?=[a-z].*)[a-z_\d]{4,20}$
```
![image](https://user-images.githubusercontent.com/84055731/141876885-33e544c5-80e0-4094-886b-7aecf8a4e5bb.png)

> 비밀번호 (usersPw) - 준성
```text
^(?=.*[a-zA-Z])(?=.*\d)(?=.*[-_~!@#$%^&*=+/,.<>;’”\(\)\[\]\{\}\?])[a-zA-Z-_~!@#$%^&*=+/,.<>;’”\(\)\[\]\{\}\?]{4,20}$
```
![image](https://user-images.githubusercontent.com/84055731/141877052-fde469dd-1a69-4a8f-a8c7-ae0ec4b72914.png)

> 이메일 (usersEmail) - 준성
```text
^[a-zA-Z0-9]([-_.]?[a-zA-Z0-9])*@[a-zA-Z0-9]([-_.]?[a-zA-Z0-9])*\.([a-zA-Z])+$
```
![image](https://user-images.githubusercontent.com/84055731/141877222-dd7e7f7a-7338-400c-bcc6-9ef720cae10d.png)

> 닉네임 (usersNick) - 선아
```text
^[a-zA-Zㄱ-ㅎ가-힣0-9]{2,10}$
```
![image](https://user-images.githubusercontent.com/84055731/141877245-55b9a6fd-f712-491a-b650-7fa4cfefacbb.png)

> 폰번호 (usersPhone) - 선아
```text
^\d{12}$
```
![image](https://user-images.githubusercontent.com/84055731/141877264-7648ca77-a7c9-466b-a188-3e70a97a28a5.png)

**Comment by seonamin** [comment]
컬럼 별 제약조건까지 결정 완료 수정본.

>아이디 (usersId) - 준성/선아

^(?=[a-z].*)[a-z_0-9]{4,20}$
![image](https://user-images.githubusercontent.com/88869283/142139485-335013fc-36db-448e-bb3c-5de14c133218.png)


>비밀번호 (usersPw) - 준성/선아

^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[_-~!@#$%^&*=+/,.;’”?])[a-zA-Z0-9_-~!@#$%^&*=+/,.;’”?]{4,20}$
![image](https://user-images.githubusercontent.com/88869283/142139290-0c758d31-d466-4330-8bde-9de920f0aa22.png)


>이메일 (usersEmail) - 준성

^[a-zA-Z0-9]([-_.]?[a-zA-Z0-9])*@[a-zA-Z0-9]([-_.]?[a-zA-Z0-9])*\.([a-zA-Z])+$
![image](https://user-images.githubusercontent.com/88869283/142139348-9521b2d9-8980-4c57-bf4a-583d80853e33.png)


>닉네임 (usersNick) - 선아

^[a-zA-Zㄱ-ㅎ가-힣0-9]{2,10}$
![image](https://user-images.githubusercontent.com/88869283/142139385-0d90f31d-2029-45cb-be52-426b5eb50c6a.png)


>폰번호 (usersPhone) - 선아

^(01[016-9])[0-9]{4}[0-9]{4}$
![image](https://user-images.githubusercontent.com/88869283/142139532-89e056dc-7c83-43b8-b6d4-8682b7fe0dac.png)
