### ISSUE TITLE
API로부터 획득한 JSON Parsing 모듈 생성

### ISSUE THREAD

**Issue by EUIDONGKIM** [daanta-real/Hexagram_semi#43]
API로부터 획득한 JSON Parsing 모듈 생성
- 작업내용: 뽑아낸 데이터를 바탕으로 JSP를 통해서 API의 데이터를 Parsing하여 언제든지 가져다쓸 수 있게 JAVA 파일을 모듈화시키기
- 목표 결과물: Utils,Dao,Dto 생성
- 참고사항: 여기서 Dao는 기존의 CRRUD와 구조가 다르다. => 공공 데이터를 빼오는 것이므로 필요한 데이터를 조회하기 위한 파라미터를 생성하는 메소드 /  조회 및 상세 조회인 R의 메소드 가 있음.

API로 데이터를 뽑아서 최종 모듈화를 시켜봤습니다.
아직 없는 기능도 많지만 한번 확인부탁드립니다.

**Comment by daanta-real** [comment]
글제목을 간소화시켜 보았습니다
- 변경 전: 뽑아낸 데이터를 바탕으로 JSP를 통해서 API의 데이터를 Parsing하여 언제든지 가져다쓸 수 있게 JAVA 파일을 모듈화시키기(Utils,Dao,Dto 생성 -> 다만 여기서 Dao는 기존의 CRRUD와는 다르다.)
- 변경 후: API로부터 획득한 JSON Parsing 모듈 생성
