### ISSUE TITLE
완성된 API 모듈을 jsp에서 사용하기 실습

### ISSUE THREAD

**Issue by EUIDONGKIM** [daanta-real/Hexagram_semi#45]
모듈화를 완성하고, 검색기능을 구현하고 a 혹은 form 태그를 활용하여 페이지끼리의 관계를 구현하였습니다.
추가적으로 더 기능을 구현하고 아이디어를 확장시키기 위해서 조원들과 토론하길 원합니다.
우선 사진으로 내용 구현을 공유합니다,

**Comment by EUIDONGKIM** [comment]
![1](https://user-images.githubusercontent.com/88869170/137604076-44d9cb0d-b223-4a5e-96e5-62c8c39a0632.JPG)
메뉴화면에서 API의 지역코드에서 뽑아와서 총 17정도 됩니다.
이를 먼저 선택하고 검색하면 시구군 과 검색 개수를 선택할 수 있습니다.

**Comment by EUIDONGKIM** [comment]
![2](https://user-images.githubusercontent.com/88869170/137604091-dc4c14a6-c3f3-478b-8283-b1c208f06bf1.JPG)
검색을 하면 parsing을 통해서 대략 13개정도의 정보를 저장할 수 있는 Dto가 만들어지는데 이안에 내용을 담아서 사용하거나 PK를 이용하여 데이터를 뿌리고 조합하는데 사용할 수 있습니다.

**Comment by EUIDONGKIM** [comment]
![image](https://user-images.githubusercontent.com/88869170/137604125-ee312b23-1da6-41eb-8fcf-4b7ea257c215.png)
단일조회 상세를 누르면
Dto에 보관될 수 있는 데이터를 Pk정보 또는 기존에 저장되있는 것을 넘겨서 합치는 과정을 거쳤습니다.
따라서 검색되는 모든 데이터는 단일조회를 누를때마다 그 정보가 다르게 보입니다.(구현 페이지는 JSP파일 1페이지)

또한 카카오 지도(JSP 파일에 한번에 사용)는DB에 있는 mapx,mapy의 정보를 Pharsing하였기때문에 Dto에 저장된 값 혹은 PK로 불러와서 처리가 가능하게 됩니다.

**Comment by EUIDONGKIM** [comment]
![image](https://user-images.githubusercontent.com/88869170/137604160-d4e6c42a-0dec-4991-935d-8dd89da00355.png)

마지막으로 DB주변 목록은 현재 관광지의 반경 1km내의 관광지 목록을 데이터베이서에서 그대로 끌어쓴 것입니다.

이 부분은 다양한 기능 사용할 수도 있을 것같아 넣어놔봤습니다.

현재 공공 API3.0은 1개의 키로 약 18개의 오퍼레이션을 사용하여 / 또한 지역코드 문화코드 숙박 관광지 축제 공공시설 모든걸 망라한 데이터를 가지고 있기때문에 이 API하나로 원하는 정보를 손쉽게 얻을 수 있을 것 같습니다.

그리고 제가 이번에 구현한 것은 관광지 contentidType=12인 것만 지정해서 나타냈기 때문에

그 이외의 항목들이 추가된다면 엄청 광범위하고 기능과 작업량이 방대해질 것으로 예상됩니다.

또한 공공Data는 JAVA조회 알고리즘에 따라서 사용범위가 제한되는 점도 고려해야할 듯 합니다.

마지막으로 검색을 통한 DB 조회(검색어 : 강원,경기,서울 ...) 도 처음에 언급하엿듯이 가능합니다. 다만 조회 알고리즘에서 DB를 더 많이 확인해야하므로, 저는 1~2시간만 TEst했는데도 막혀버렸습니다. 편리하긴 하지만 이부분도 같이 생각해보면 좋을 것 같습니다.
이상입니다.

**Comment by daanta-real** [comment]
글제목을 간소화시켜 보았습니다
변경 전: 모듈화를 완성하고, 검색기능을 구현하고 a 혹은 form 태그를 활용하여 페이지끼리의 관계를 구현한다. 추가적으로 더 기능을 구현하고 아이디어를 확장시키기 위해서 조원들과 토론하길 원합니다
변경 후: 완성된 API 모듈을 jsp에서 사용하기 실습
